version: "3"
 services:
   nginx:
    image: nginx:1.17.4-alpine
    container_name: nginx
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - drupal-data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - external
###########################################################################################################################  
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file: .env
    networks:
      - internal
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
##########################################################################################################################
   drupal:
    image: drupal:8.7.8-fpm-alpine
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html
 #####################################################################################################################
   certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - drupal-data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email mulugetadawit55@gmail.com --agree-tos --no-eff-email --force-renewal -d  drupal.3.110.209.93.nip.io -d www.drupal.3.110.209.93.nip.io
   php:
    container_name: php
    image: php:8.0-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
#################################################################################################################################################
   redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

 networks:
  external:
    driver: bridge
  internal:
    driver: bridge

 volumes:
  drupal-data:
  db-data:
  certbot-etc:
